apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: fpbe-monitoring
version: 1.0.0
description: Monitoring stack for FPBE mobile banking system including Prometheus, Grafana, and AlertManager
type: application
appVersion: 1.0.0

# Dependencies for the monitoring stack
dependencies:
  - name: prometheus
    version: 2.45.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    tags:
      - monitoring
      - metrics
    import-values:
      - "*"
  
  - name: grafana
    version: 9.0.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    tags:
      - visualization
      - dashboards
    import-values:
      - "*"
  
  - name: alertmanager
    version: 0.25.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
    tags:
      - alerting
      - notifications
    import-values:
      - "*"

# Chart metadata
maintainers:
  - name: FPBE DevOps Team
    email: devops@fpbe.com

keywords:
  - monitoring
  - prometheus
  - grafana
  - alertmanager
  - observability
  - metrics
  - logging
  - alerts

home: https://github.com/fpbe/mobile-banking
sources:
  - https://github.com/fpbe/mobile-banking

# Template engine
engine: gotpl