apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - name: bitcoin
        image: your-dockerhub/bitcoin-node:latest
        ports:
        - containerPort: 8332
        env:
        - name: BTC_API_SECRET
          valueFrom:
            secretKeyRef:
              name: project-secrets
              key: BTC_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin
spec:
  selector:
    app: bitcoin
  ports:
    - protocol: TCP
      port: 8332
      targetPort: 8332
