apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-sdk
  template:
    metadata:
      labels:
        app: ethereum-sdk
    spec:
      containers:
      - name: ethereum-sdk
        image: your-dockerhub/ethereum-sdk:latest
        ports:
        - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ethereum-sdk
spec:
  selector:
    app: ethereum-sdk
  ports:
    - protocol: TCP
      port: 8545
      targetPort: 8545
