apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
      - name: frontend
        image: your-dockerhub/frontend-dev:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-dev
spec:
  selector:
    app: frontend-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
