apiVersion: v1
kind: Secret
metadata:
  name: project-secrets
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=          # base64 dari 'postgres'
  API_KEY: YXBpa2V5MTIz               # base64 dari 'apikey123'
  BTC_API_SECRET: c2VjcmV0            # base64 dari 'secret'
