apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-banking
  template:
    metadata:
      labels:
        app: voice-banking
    spec:
      containers:
      - name: voice-banking
        image: your-dockerhub/voice-banking:latest
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: voice-banking
spec:
  selector:
    app: voice-banking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
