apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "api-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: fpbe
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "api-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "api-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: fpbe
      annotations:
        prometheus.io/scrape: {{ .Values.deployment.annotations."prometheus.io/scrape" | quote }}
        prometheus.io/port: {{ .Values.deployment.annotations."prometheus.io/port" | quote }}
        sidecar.istio.io/inject: {{ .Values.deployment.annotations."sidecar.istio.io/inject" | quote }}
        vault.hashicorp.com/agent-inject: {{ .Values.deployment.annotations."vault.hashicorp.com/agent-inject" | quote }}
        vault.hashicorp.com/role: {{ .Values.deployment.annotations."vault.hashicorp.com/role" | quote }}
    spec:
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "api-gateway.serviceAccountName" . }}
      containers:
        - name: kong
          image: "kong:{{ .Values.kong.version }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          ports:
            - name: proxy
              containerPort: {{ .Values.kong.proxy.http.containerPort }}
              protocol: TCP
            - name: proxy-ssl
              containerPort: {{ .Values.kong.proxy.tls.containerPort }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.kong.admin.http.containerPort }}
              protocol: TCP
            - name: metrics
              containerPort: 9542
              protocol: TCP
          env:
            - name: KONG_DATABASE
              value: {{ .Values.kong.env.database | quote }}
            - name: KONG_PROXY_ACCESS_LOG
              value: {{ .Values.kong.env.proxy_access_log | quote }}
            - name: KONG_ADMIN_ACCESS_LOG
              value: {{ .Values.kong.env.admin_access_log | quote }}
            - name: KONG_PROXY_ERROR_LOG
              value: {{ .Values.kong.env.proxy_error_log | quote }}
            - name: KONG_ADMIN_ERROR_LOG
              value: {{ .Values.kong.env.admin_error_log | quote }}
            - name: KONG_ADMIN_LISTEN
              value: {{ .Values.kong.env.admin_listen | quote }}
            - name: KONG_PROXY_LISTEN
              value: {{ .Values.kong.env.proxy_listen | quote }}
            - name: KONG_SSL_CERT
              value: {{ .Values.kong.env.ssl_cert | quote }}
            - name: KONG_SSL_CERT_KEY
              value: {{ .Values.kong.env.ssl_cert_key | quote }}
            - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
              value: {{ .Values.kong.env.lua_ssl_trusted_certificate | quote }}
            - name: KONG_REAL_IP_HEADER
              value: {{ .Values.kong.env.real_ip_header | quote }}
            - name: KONG_REAL_IP_RECURSIVE
              value: {{ .Values.kong.env.real_ip_recursive | quote }}
            - name: KONG_TRUSTED_IPS
              value: {{ .Values.kong.env.trusted_ips | quote }}
            - name: KONG_SSL_PROTOCOLS
              value: {{ .Values.kong.env.ssl_protocols | quote }}
            - name: KONG_SSL_PREFER_SERVER_CIPHERS
              value: {{ .Values.kong.env.ssl_prefer_server_ciphers | quote }}
            - name: KONG_SSL_SESSION_TICKETS
              value: {{ .Values.kong.env.ssl_session_tickets | quote }}
          resources:
            {{- toYaml .Values.kong.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.kong.proxy.http.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.kong.proxy.http.containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: kong-tls
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: kong-config
          configMap:
            name: {{ include "api-gateway.fullname" . }}-config
        - name: ssl-certs
          secret:
            secretName: {{ include "api-gateway.fullname" . }}-certs
        - name: kong-tls
          secret:
            secretName: {{ .Values.ingress.tls.secretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}