apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "api-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: fpbe-banking
    helm.sh/chart: {{ include "api-gateway.chart" . }}
  annotations:
    # Prometheus monitoring annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
    # AWS Load Balancer configurations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.sslCertArn | quote }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    # Additional security headers
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment={{ .Release.Namespace }},Component=api-gateway"

spec:
  type: LoadBalancer
  # Port configurations for different services
  ports:
    # Main proxy port for HTTP traffic
    - name: proxy
      port: 80
      targetPort: 8000
      protocol: TCP
    # SSL port for HTTPS traffic
    - name: proxy-ssl
      port: 443
      targetPort: 8443
      protocol: TCP
    # Admin API port (restricted access)
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
    # Prometheus metrics port
    - name: metrics
      port: 9542
      targetPort: 9542
      protocol: TCP
  # Pod selector based on Kong deployment labels
  selector:
    app.kubernetes.io/name: {{ include "api-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  # Session affinity for consistent routing
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hour timeout
  # External traffic policy for better security
  externalTrafficPolicy: Local
  # Health check configuration
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort | default 0 }}
  # Load balancer source ranges if specified
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}