apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-service.fullname" . }}
  labels:
    {{- include "pi-service.labels" . | nindent 4 }}
  annotations:
    # Enable Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.metricsPort | quote }}
    # Add service mesh annotations for enhanced traffic management
    service.istio.io/canonical-name: {{ include "pi-service.fullname" . }}
    service.istio.io/canonical-revision: {{ .Values.image.tag | quote }}
    # Add monitoring annotations for service health tracking
    monitoring.fpbe.com/port: {{ .Values.service.port | quote }}
    monitoring.fpbe.com/path: "/health"

spec:
  type: {{ .Values.service.type }}
  # Define ports for both application traffic and metrics
  ports:
    # Main application port for Pi Network integration service
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # Metrics port for Prometheus monitoring
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  # Use precise pod selection for reliable service targeting
  selector:
    {{- include "pi-service.selectorLabels" . | nindent 4 }}