[programs.localnet]
teos_mining = "AhXBUQmbhv9dNoZCiMYmXF4Gyi1cjQthWHFhTL2CJaSo"

[programs.devnet]
teos_mining = "AhXBUQmbhv9dNoZCiMYmXF4Gyi1cjQthWHFhTL2CJaSo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf"

[registry]
url = "https://anchor.projectserum.com"

[workspace]
members = ["programs/teos_mining"]

[test.validator]
url = "https://api.devnet.solana.com"
