# FPBE Mobile Banking Application ConfigMaps
# Version: 1.0.0
# Enhanced configuration management for microservices with security controls

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  labels:
    app: fpbe
    service: account-service
    version: "1.0.0"
  annotations:
    description: "Account service configuration with enhanced security and monitoring"
data:
  application.yml: |
    spring:
      application:
        name: account-service
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            batch_size: 100
            fetch_size: 100
            connection:
              pool_size: 50
            query:
              plan_cache_max_size: 2048
              plan_parameter_metadata_max_size: 128
    
    management:
      endpoints:
        web:
          exposure:
            include: health,metrics,prometheus
        health:
          probes:
            enabled: true
        metrics:
          tags:
            application: account-service
    
    logging:
      level:
        root: INFO
        com.fpbe.account: DEBUG
      pattern: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
      file: /var/log/fpbe/account-service.log
    
    resilience4j:
      circuitbreaker:
        instances:
          accountService:
            failureRateThreshold: 50
            waitDurationInOpenState: 60s
            permittedNumberOfCallsInHalfOpenState: 10
            slidingWindowSize: 100
            minimumNumberOfCalls: 20

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pi-service-config
  labels:
    app: fpbe
    service: pi-service
    version: "1.0.0"
  annotations:
    description: "Pi Network service configuration with enhanced mining controls"
data:
  pi-config.json: |
    {
      "mining": {
        "defaultRate": 0.25,
        "maxRate": 1.0,
        "minRate": 0.1,
        "sessionTimeout": 3600,
        "maxSessionsPerUser": 1,
        "cooldownPeriod": 300,
        "rateLimits": {
          "requestsPerMinute": 60,
          "sessionsPerDay": 24
        },
        "validation": {
          "enabled": true,
          "checksumVerification": true
        }
      },
      "network": {
        "mainnet": {
          "rpcEndpoint": "https://api.mainnet.pi",
          "wsEndpoint": "wss://ws.mainnet.pi",
          "explorerUrl": "https://explorer.pi",
          "timeout": 30000,
          "retryAttempts": 3,
          "healthCheck": {
            "enabled": true,
            "interval": 60
          }
        }
      },
      "security": {
        "encryption": {
          "enabled": true,
          "algorithm": "AES-256-GCM"
        },
        "audit": {
          "enabled": true,
          "logPath": "/var/log/fpbe/audit/pi-service.log"
        }
      },
      "logging": {
        "level": "info",
        "format": "json",
        "piNetworkEvents": true,
        "retention": "30d"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app: fpbe
    service: notification-service
    version: "1.0.0"
  annotations:
    description: "Notification service configuration with rate limiting and security"
data:
  config.yaml: |
    service:
      name: notification-service
      environment: production
      logLevel: INFO
    
    email:
      templates:
        2fa_code: "email_2fa_template"
        transaction_alert: "transaction_alert_template"
      retry_policy:
        max_retries: 3
        retry_delay: 5
    
    sms:
      templates:
        2fa_code: "Your FPBE verification code is: {}"
        transaction_alert: "FPBE Alert: Transaction of {} detected"
      rate_limit:
        max_per_number: 5
        window_seconds: 3600
    
    push:
      fcm:
        ttl: 2419200
      apns:
        use_sandbox: false
      categories:
        transaction:
          priority: high
          ttl: 3600
        2fa:
          priority: high
          ttl: 120
        marketing:
          priority: normal
          ttl: 86400

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  labels:
    app: fpbe
    component: monitoring
    version: "1.0.0"
  annotations:
    description: "Monitoring configuration for metrics collection and alerting"
data:
  prometheus-rules.yaml: |
    groups:
      - name: fpbe_alerts
        rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: High error rate detected
          - alert: ServiceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: Service is down
  
  grafana-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        version: 1
        editable: false