# Kubernetes Secrets configuration for FPBE Mobile Banking Application
# Version: v1
# This file contains sensitive configuration data and must be handled with appropriate security controls

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: fpbe-banking
  labels:
    app: fpbe-banking
    component: database
  annotations:
    kubernetes.io/rotation-period: "30d"
type: Opaque
data:
  POSTGRES_USERNAME: cG9zdGdyZXNfdXNlcg==  # postgres_user
  POSTGRES_PASSWORD: UDBzdGdyM3NQQHNzdzByZA==  # P0stgr3sP@ssw0rd
  POSTGRES_CONNECTION_STRING: cG9zdGdyZXNxbDovL3Bvc3RncmVzX3VzZXI6UDBzdGdyM3NQQHNzdzByZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZnBiZV9iYW5raW5n
  MONGODB_USERNAME: bW9uZ29fYWRtaW4=  # mongo_admin
  MONGODB_PASSWORD: TTBuZzBEQlBAc3N3MHJk  # M0ng0DBP@ssw0rd
  MONGODB_CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9tb25nb19hZG1pbjpNMG5nMERCUEBzc3cwcmRAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L2ZwYmVfYmFua2luZw==
  REDIS_PASSWORD: UjNkaXNQQHNzdzByZA==  # R3disP@ssw0rd

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: fpbe-banking
  labels:
    app: fpbe-banking
    component: auth
  annotations:
    kubernetes.io/rotation-period: "90d"
type: Opaque
data:
  JWT_SECRET_KEY: ZnBiZV9qd3Rfc2VjcmV0X2tleV8yMDIz
  JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ==
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0=
  REFRESH_TOKEN_SECRET: ZnBiZV9yZWZyZXNoX3Rva2VuX3NlY3JldF8yMDIz
  TOKEN_ENCRYPTION_KEY: ZnBiZV90b2tlbl9lbmNyeXB0aW9uX2tleV8yMDIz

---
apiVersion: v1
kind: Secret
metadata:
  name: pi-network-secrets
  namespace: fpbe-banking
  labels:
    app: fpbe-banking
    component: pi-network
  annotations:
    kubernetes.io/rotation-period: "90d"
type: Opaque
data:
  PI_API_KEY: cGlfbmV0d29ya19hcGlfa2V5XzIwMjM=
  PI_API_SECRET: cGlfbmV0d29ya19hcGlfc2VjcmV0XzIwMjM=
  PI_WALLET_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  PI_WALLET_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0=
  PI_MINING_CONFIG: eyJtaW5pbmdSYXRlIjoiMC4yNSIsIm1pbmluZ0ludGVydmFsIjoiMzYwMCJ9
  PI_NODE_SECRET: cGlfbm9kZV9zZWNyZXRfMjAyMw==

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: fpbe-banking
  labels:
    app: fpbe-banking
    component: notifications
  annotations:
    kubernetes.io/rotation-period: "90d"
type: Opaque
data:
  SMTP_USERNAME: bm90aWZpY2F0aW9uc0BmcGJlLmNvbQ==
  SMTP_PASSWORD: U210cFBAc3N3MHJkMjAyMw==
  FCM_SERVER_KEY: ZmNtX3NlcnZlcl9rZXlfMjAyMw==
  APNS_KEY_ID: YXBuc19rZXlfaWRfMjAyMw==
  APNS_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t
  TWILIO_ACCOUNT_SID: dHdpbGlvX2FjY291bnRfc2lkXzIwMjM=
  TWILIO_AUTH_TOKEN: dHdpbGlvX2F1dGhfdG9rZW5fMjAyMw==

---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secrets
  namespace: fpbe-banking
  labels:
    app: fpbe-banking
    component: security
  annotations:
    kubernetes.io/rotation-period: "30d"
type: Opaque
data:
  AES_256_MASTER_KEY: YWVzXzI1Nl9tYXN0ZXJfa2V5XzIwMjM=
  AES_256_ROTATION_KEY: YWVzXzI1Nl9yb3RhdGlvbl9rZXlfMjAyMw==
  HSM_PARTITION_ID: aHNtX3BhcnRpdGlvbl9pZF8yMDIz
  HSM_ADMIN_PASSWORD: SFNNQWRtaW5QQHNzdzByZDIwMjM=
  HSM_CRYPTO_USER_PASSWORD: SFNNVXNlclBAc3N3MHJkMjAyMw==
  FIELD_LEVEL_ENCRYPTION_KEY: ZmllbGRfbGV2ZWxfZW5jcnlwdGlvbl9rZXlfMjAyMw==