# Istio Service Mesh Configuration v1.18
# FPBE Mobile Banking Application Service Mesh Configuration

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: fpbe-mesh-config
  namespace: fpbe
  labels:
    app: fpbe
    component: service-mesh
    part-of: fpbe
    version: "1.0"
    environment: production
spec:
  profile: default
  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      label:
        app: fpbe-gateway
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        custom_tags:
          user_id:
            header:
              name: x-user-id
          transaction_id:
            header:
              name: x-transaction-id
          service_version:
            literal:
              value: "1.0"
          environment:
            literal:
              value: "production"
    accessLogFile: /dev/stdout
    accessLogFormat: |
      {
        "protocol": "%PROTOCOL%",
        "upstream_service": "%UPSTREAM_SERVICE%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "user_id": "%REQ(X-USER-ID)%",
        "duration": "%DURATION%",
        "authority": "%REQ(:AUTHORITY)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%"
      }
    enableAutoMtls: true
    trustDomain: fpbe.com
    defaultServiceSettings:
      loadBalancer:
        simple: ROUND_ROBIN
      connectionPool:
        tcp:
          maxConnections: 100
          connectTimeout: 30ms
          tcpKeepalive:
            time: 10s
            interval: 10s
            probes: 3
        http:
          http1MaxPendingRequests: 1024
          maxRequestsPerConnection: 10
          maxRetries: 3
          idleTimeout: 15s
          h2MaxRequests: 1000

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: fpbe-mtls-policy
  namespace: fpbe
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app: fpbe
  portLevelMtls:
    8000:
      mode: STRICT
    8001:
      mode: STRICT

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: fpbe-destination-rule
  namespace: fpbe
spec:
  host: "*.fpbe.svc.cluster.local"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
      consistentHash:
        httpHeaderName: x-user-id
        minimumRingSize: 1024
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 30ms
        tcpKeepalive:
          time: 10s
          interval: 10s
          probes: 3
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 10
        maxRetries: 3
        idleTimeout: 15s
        h2MaxRequests: 1000
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 10
      minHealthPercent: 50
    tls:
      mode: ISTIO_MUTUAL
      minProtocolVersion: TLSV1_3
      cipherSuites:
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-service-policy
  namespace: fpbe
spec:
  selector:
    matchLabels:
      app: auth-service
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/fpbe/sa/api-gateway"]
    to:
    - operation:
        methods: ["POST", "GET"]
        paths: ["/api/v1/auth/*"]
    when:
    - key: request.headers[x-api-key]
      values: ["*"]

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: transaction-service-policy
  namespace: fpbe
spec:
  selector:
    matchLabels:
      app: transaction-service
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/fpbe/sa/api-gateway", "cluster.local/ns/fpbe/sa/account-service"]
    to:
    - operation:
        methods: ["POST", "GET", "PUT"]
        paths: ["/api/v1/transactions/*"]
    when:
    - key: request.auth.claims[roles]
      values: ["admin", "user"]

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fpbe-virtual-service
  namespace: fpbe
spec:
  hosts:
  - "api.fpbe.com"
  gateways:
  - fpbe-gateway
  http:
  - match:
    - uri:
        prefix: "/api/v1/auth"
    route:
    - destination:
        host: auth-service
        port:
          number: 3000
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 2s
  - match:
    - uri:
        prefix: "/api/v1/transactions"
    route:
    - destination:
        host: transaction-service
        port:
          number: 3000
    timeout: 10s
    retries:
      attempts: 5
      perTryTimeout: 2s
  - match:
    - uri:
        prefix: "/api/v1/pi"
    route:
    - destination:
        host: pi-service
        port:
          number: 3000
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 5s

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: fpbe-gateway
  namespace: fpbe
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: fpbe-tls-cert
    hosts:
    - "api.fpbe.com"