---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fpbe
  labels:
    app: fpbe
    component: transaction-service
    part-of: fpbe-banking
    version: 1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fpbe
      component: transaction-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
        sidecar.istio.io/inject: "true"
      labels:
        app: fpbe
        component: transaction-service
        version: 1.0.0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: fpbe
                component: transaction-service
            topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      containers:
      - name: transaction-service
        image: fpbe/transaction-service:1.0.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 8083
        - name: metrics
          containerPort: 8084
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8083"
        - name: KAFKA_SERVERS
          valueFrom:
            configMapKeyRef:
              name: transaction-service-config
              key: kafka.bootstrap-servers
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: transaction-service-config
              key: database.host
        volumeMounts:
        - name: transaction-service-config
          mountPath: /app/config
          readOnly: true
        - name: transaction-service-secrets
          mountPath: /app/secrets
          readOnly: true
        - name: tmp
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
      volumes:
      - name: transaction-service-config
        configMap:
          name: transaction-service-config
      - name: transaction-service-secrets
        secret:
          secretName: transaction-service-secrets
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: fpbe
  labels:
    app: fpbe
    component: transaction-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: metrics
    port: 8084
    targetPort: 8084
  selector:
    app: fpbe
    component: transaction-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-service-hpa
  namespace: fpbe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: transaction-service-pdb
  namespace: fpbe
spec:
  minAvailable: "75%"
  selector:
    matchLabels:
      app: fpbe
      component: transaction-service
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transaction-service-network-policy
  namespace: fpbe
spec:
  podSelector:
    matchLabels:
      app: fpbe
      component: transaction-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: fpbe
          component: api-gateway
    ports:
    - protocol: TCP
      port: 8083
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: fpbe
          component: postgres
    - podSelector:
        matchLabels:
          app: fpbe
          component: kafka