# Prometheus Configuration for FPBE Mobile Banking System
# Version: 2.45.0

# Global configuration settings
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: production
    region: global

# Scrape configurations for all services
scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['api-gateway:9090']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['account-service:8080']

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['transaction-service:8080']

  - job_name: 'pi-service'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['pi-service:9090']

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      cert_file: '/etc/prometheus/certs/client.crt'
      key_file: '/etc/prometheus/certs/client.key'
      ca_file: '/etc/prometheus/certs/ca.crt'
    static_configs:
      - targets: ['notification-service:9090']

# Alerting configuration
alerting:
  alertmanagers:
    - scheme: 'https'
      tls_config:
        cert_file: '/etc/prometheus/certs/client.crt'
        key_file: '/etc/prometheus/certs/client.key'
        ca_file: '/etc/prometheus/certs/ca.crt'
      static_configs:
        - targets: ['alertmanager:9093']

# Rule files for alerts and recording rules
rule_files:
  - 'rules/service_alerts.yml'
  - 'rules/pi_mining_alerts.yml'

# Storage configuration
storage:
  tsdb:
    retention_time: '15d'
    retention_size: '50GB'
    wal_compression: true
    min_block_duration: '2h'
    max_block_duration: '24h'

# Web UI configuration
web:
  listen_address: '0.0.0.0:9090'
  external_url: 'https://prometheus.fpbe.com'
  max_connections: 512
  read_timeout: '30s'
  max_samples_per_query: 50000000
  page_title: 'FPBE Prometheus Monitoring'