version: "3"
services:
  aml-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/aml
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
