# Default values for pi-service Helm chart
# This is a YAML-formatted file.

# Number of replicas for the Pi service deployment
replicaCount: 3

# Override name of the chart
nameOverride: ""
# Override full name of the chart
fullnameOverride: ""

# Container image configuration
image:
  repository: fpbe/pi-service
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets for private registries
imagePullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 3000
  metricsPort: 9090

# Resource requests and limits for the container
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Pod annotations for service mesh and metrics collection
podAnnotations:
  sidecar.istio.io/inject: "true"
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

# Security context for the container
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Liveness probe configuration
livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# ConfigMap reference
configMap:
  name: pi-service-config

# Secret reference
secret:
  name: pi-service-secrets

# Environment variables
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: "info"
  - name: METRICS_PORT
    value: "9090"

# Pod affinity rules for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              component: pi-service
          topologyKey: kubernetes.io/hostname

# Node tolerations
tolerations:
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"

# Update strategy configuration
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0