apiVersion: v2
name: fpbe-istio
description: FPBE-specific Istio service mesh configuration providing secure communication, monitoring, and traffic management for mobile banking services with PCI-DSS compliance, mTLS encryption, and comprehensive observability features for the FPBE mobile banking platform
version: 1.0.0
appVersion: 1.18.0
type: application

# External chart dependencies
dependencies:
  - name: istio-base
    version: 1.18.0
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio-base.enabled
    tags:
      - infrastructure
      - security

  - name: istiod
    version: 1.18.0
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istiod.enabled
    tags:
      - control-plane
      - security

  - name: istio-ingress
    version: 1.18.0
    repository: https://istio-release.storage.googleapis.com/charts
    condition: ingress.enabled
    tags:
      - ingress
      - security

# Chart metadata
keywords:
  - istio
  - service-mesh
  - security
  - monitoring
  - fpbe
  - banking
  - pci-dss
  - mobile-banking

maintainers:
  - name: FPBE Platform Team
    email: platform@fpbe.com

# Additional metadata
home: https://fpbe.com
sources:
  - https://github.com/fpbe/fpbe-istio

# Annotations for security and compliance
annotations:
  security.fpbe.com/pci-dss: "compliant"
  security.fpbe.com/mtls: "strict"
  monitoring.fpbe.com/prometheus: "enabled"
  monitoring.fpbe.com/grafana: "enabled"

# Engine constraints
kubeVersion: ">=1.24.0"