---
# Ansible tasks for implementing comprehensive security infrastructure
# ansible.builtin version: 2.15+
# community.aws version: 6.0+
# community.kubernetes version: 2.0+

- name: Verify environment variables and prerequisites
  ansible.builtin.assert:
    that:
      - env is defined
      - vault_version is defined
      - waf_rules_path is defined
      - siem_endpoint is defined
      - hsm_partition is defined
      - compliance_log_retention is defined
    fail_msg: "Required environment variables are not set"

- name: Setup Hardware Security Module (HSM)
  block:
    - name: Install HSM client packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - safenet-hsm-client
        - openssl
        - cryptsetup
      tags: [hsm, security]

    - name: Configure HSM network settings
      ansible.builtin.template:
        src: hsm-client.conf.j2
        dest: /etc/hsm/client.conf
        mode: '0600'
      notify: rotate_keys

    - name: Initialize HSM partition
      ansible.builtin.command:
        cmd: "lunacm partition init -label {{ hsm_partition }}"
      register: hsm_init
      changed_when: hsm_init.rc == 0
      failed_when: hsm_init.rc != 0 and 'already initialized' not in hsm_init.stderr

    - name: Setup HSM audit logging
      ansible.builtin.template:
        src: hsm-audit.conf.j2
        dest: /etc/hsm/audit.conf
        mode: '0600'
  tags: [hsm, security]

- name: Setup Web Application Firewall (WAF)
  block:
    - name: Install ModSecurity and dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - modsecurity
        - modsecurity-crs
        - nginx

    - name: Configure WAF rules
      ansible.builtin.template:
        src: modsecurity.conf.j2
        dest: "{{ waf_rules_path }}/modsecurity.conf"
        mode: '0644'
      notify: reload_waf

    - name: Deploy custom banking rules
      ansible.builtin.template:
        src: banking-rules.conf.j2
        dest: "{{ waf_rules_path }}/banking-rules.conf"
        mode: '0644'
      notify: reload_waf

    - name: Setup WAF monitoring
      ansible.builtin.template:
        src: waf-monitoring.conf.j2
        dest: /etc/modsecurity/monitoring.conf
        mode: '0644'
  tags: [waf, security]

- name: Setup Security Information and Event Management (SIEM)
  block:
    - name: Deploy SIEM collectors
      ansible.builtin.template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'
      notify: restart_siem

    - name: Configure SIEM alert rules
      ansible.builtin.template:
        src: siem-alerts.yml.j2
        dest: /etc/siem/alerts.yml
        mode: '0644'

    - name: Setup compliance reporting
      ansible.builtin.template:
        src: compliance-reports.yml.j2
        dest: /etc/siem/compliance.yml
        mode: '0644'

    - name: Configure log retention
      ansible.builtin.lineinfile:
        path: /etc/siem/retention.conf
        line: "retention.days: {{ compliance_log_retention }}"
        create: yes
  tags: [siem, monitoring, compliance]

- name: Setup HashiCorp Vault
  block:
    - name: Deploy Vault container
      community.kubernetes.k8s:
        state: present
        definition: "{{ lookup('template', 'vault-deployment.yml.j2') | from_yaml }}"

    - name: Initialize Vault
      ansible.builtin.command:
        cmd: "vault operator init -recovery-shares=5 -recovery-threshold=3"
      register: vault_init
      changed_when: vault_init.rc == 0
      failed_when: vault_init.rc != 0 and 'already initialized' not in vault_init.stderr

    - name: Configure Vault audit logging
      ansible.builtin.command:
        cmd: "vault audit enable file file_path=/var/log/vault/audit.log"
      register: vault_audit
      changed_when: vault_audit.rc == 0
      failed_when: vault_audit.rc != 0 and 'already enabled' not in vault_audit.stderr

    - name: Setup Vault policies
      ansible.builtin.template:
        src: vault-policies.hcl.j2
        dest: /etc/vault/policies/
        mode: '0644'
      notify: restart_vault
  tags: [vault, security]

handlers:
  - name: restart_vault
    ansible.builtin.service:
      name: vault
      state: restarted
      enabled: yes

  - name: reload_waf
    ansible.builtin.service:
      name: nginx
      state: reloaded

  - name: restart_siem
    ansible.builtin.service:
      name: filebeat
      state: restarted
      enabled: yes

  - name: rotate_keys
    ansible.builtin.command:
      cmd: "lunacm partition rotate -label {{ hsm_partition }}"
    register: key_rotation
    changed_when: key_rotation.rc == 0
    failed_when: key_rotation.rc != 0 and 'rotation already in progress' not in key_rotation.stderr