apiVersion: v2
name: fpbe-api-gateway
version: 1.0.0
kubeVersion: ">=1.21.0"
description: API Gateway service for FPBE mobile banking application using Kong with enhanced security and high availability
type: application
appVersion: "3.2.0"

keywords:
  - api-gateway
  - kong
  - mobile-banking
  - fpbe
  - high-availability
  - security

maintainers:
  - name: FPBE DevOps Team
    email: devops@fpbe.com

dependencies:
  - name: kong
    version: 3.2.x
    repository: https://charts.konghq.com
    condition: kong.enabled
    tags:
      - api-gateway
      - ingress-controller

annotations:
  artifacthub.io/changes: "Initial release of FPBE API Gateway with enhanced security controls"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/prerelease: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/maintainers: '[{"name":"FPBE DevOps Team","email":"devops@fpbe.com"}]'
  artifacthub.io/recommendations: '[{"url":"https://docs.konghq.com/kubernetes-ingress-controller/latest/security/"}]'

home: https://fpbe.com
sources:
  - https://github.com/fpbe/api-gateway
icon: https://fpbe.com/images/logo.png

# Engine requirements
engine: gotpl