apiVersion: v2
name: account-service
description: A Helm chart for FPBE Account Service microservice providing scalable account management with high availability and disaster recovery capabilities
version: 1.0.0
appVersion: 1.0.0
type: application
keywords:
  - account
  - banking
  - microservice
  - fpbe
  - high-availability
  - scalable
maintainers:
  - name: FPBE Team
    email: team@fpbe.com
kubeVersion: ">=1.20.0-0"
engine: gotpl

# Dependencies section defines required charts
dependencies:
  # PostgreSQL for persistent data storage with ACID compliance
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  # Redis for caching and session management
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled