# Default values for account-service
# This is a YAML-formatted file.

# Number of pod replicas for horizontal scaling with sharding strategy
replicaCount: 3

# Container image configuration
image:
  repository: fpbe/account-service
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets for private registry access
imagePullSecrets:
  - name: fpbe-registry-secret

# Pod annotations for monitoring, backup and service mesh integration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8081"
  prometheus.io/path: "/actuator/prometheus"
  backup.velero.io/backup-volumes: "data"
  sidecar.istio.io/inject: "true"

# Pod security context for non-root execution
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

# Container security context
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

# Service configuration for internal access
service:
  type: ClusterIP
  port: 8081
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# Resource allocation to meet performance requirements
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

# Health check configuration
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

# Node selection for optimal performance
nodeSelector:
  kubernetes.io/os: linux
  node.kubernetes.io/instance-type: c5.xlarge

# Tolerations for node failures and maintenance
tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300

# Affinity rules for high availability across zones
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - account-service
          topologyKey: topology.kubernetes.io/zone

# PostgreSQL dependency configuration
postgresql:
  enabled: true
  primary:
    persistence:
      size: 100Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
  replication:
    enabled: true
    readReplicas: 2
  metrics:
    enabled: true

# Redis dependency configuration
redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
  master:
    persistence:
      size: 20Gi
  replica:
    replicaCount: 2
    persistence:
      size: 20Gi
  metrics:
    enabled: true

# Application-specific configuration
config:
  spring:
    profiles:
      active: production
  logging:
    level:
      root: INFO
      com.fpbe.account: DEBUG
  management:
    endpoints:
      web:
        exposure:
          include: health,metrics,prometheus
    metrics:
      tags:
        application: account-service