apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-service.fullname" . }}
  labels:
    {{- include "transaction-service.labels" . | nindent 4 }}
  annotations:
    # Enable Prometheus metrics scraping
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    # Use AWS Network Load Balancer for better performance
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "transaction-service.selectorLabels" . | nindent 4 }}
  # Disable session affinity for better load distribution
  sessionAffinity: None
  # Don't publish pods that aren't ready
  publishNotReadyAddresses: false
  {{- if eq .Values.service.type "LoadBalancer" }}
  # Ensure high availability across availability zones
  externalTrafficPolicy: Local
  # Use internal load balancer if specified
  {{- if .Values.service.internal }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  {{- end }}
  {{- end }}